DROP TABLE IF EXISTS installation;
DROP TABLE IF EXISTS configuration;
DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS song_file;
DROP TABLE IF EXISTS stored_file;